pagination:
  per: 25
  max_per: 250
services:
  devices: 'https://devices.lelylan.com'
  types: 'https://types.lelylan.com'
  people: 'https://people.lelylan.com'
titles:
  '/users/new': Sign in
scopes:
  read:
    - resources
    - resources:read
    - devices
    - devices:read
    - devices:control
    - histories:read
    - types
    - types:read
    - privates
    - user
